version: '3'
services:
  app:
    build: ./docker
    image: app/jusbrasil
    command: bash -c 'cd tmp/teste && mvn spring-boot:run'
    volumes:
      - .:/tmp
    ports:
      - "8080:8080"
  web:
    image: node:8
    command: bash -c 'cd tmp/teste-front && yarn && yarn serve'
    volumes:
      - .:/tmp
    ports:
      - "4200:4200"
